### ISSUE TITLE
Order seeder breaks Order Reference generator

### ISSUE THREAD

**Issue by glennjacobs** [lunarphp/demo-store#20]
Because the seeder isn't conforming to the default order reference generator format, we get the following error upon placing a second order.

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/647407/160659377-d5f6456b-437d-470b-9338-06dbdc0b2a7a.png">

**Comment by alecritson** [comment]
Updated the seeder to use the reference generator GetCandy provides.

https://github.com/getcandy/demo-store/blob/next/database/seeders/OrderSeeder.php#L37
