### ISSUE TITLE
When we delete image of product from multiple collection all images are getting deleted

### ISSUE THREAD

**Issue by imrancoder** [lunarphp/demo-store#57]
![image](https://user-images.githubusercontent.com/68069779/212561195-eae3d0fb-311d-461d-a3e0-8ddf4104b2d3.png)
![image](https://user-images.githubusercontent.com/68069779/212561217-d953efbd-329d-4327-b544-2f07db956d86.png)

**Comment by glennjacobs** [comment]
Please provide instructions on how to reproduce.

**Comment by imrancoder** [comment]
> Please provide instructions on how to reproduce.

1. Seed Products
2. Add Multiple Images for single product and save
3. Delete any image from single product page and save

After this all images are deleted from folder

**Comment by alecritson** [comment]
In `config/media-library.php` can you try changing:

```php
'path_generator' => MediaPathResolver::class,
```

to 

```php
'path_generator' => Spatie\MediaLibrary\Support\PathGenerator\DefaultPathGenerator::class,
```

and see if that fixes the problem?

**Comment by imrancoder** [comment]
> In `config/media-library.php` can you try changing:
> 
> ```
> 'path_generator' => MediaPathResolver::class,
> ```
> 
> to
> 
> ```
> 'path_generator' => Spatie\MediaLibrary\Support\PathGenerator\DefaultPathGenerator::class,
> ```
> 
> and see if that fixes the problem?

No its not working with `Spatie\MediaLibrary\Support\PathGenerator\DefaultPathGenerator::class,`

and after installing lunar with `'path_generator' => MediaPathResolver::class,` 
images are loading 
![image](https://user-images.githubusercontent.com/68069779/213847730-c66a7c61-acd4-43ca-9dc5-1ae3065a964f.png)

but with `'path_generator' => Spatie\MediaLibrary\Support\PathGenerator\DefaultPathGenerator::class,` images are not loading as images are present in storage folder 
![image](https://user-images.githubusercontent.com/68069779/213847787-96dbb25b-123f-4952-a28c-8d54e361760d.png)

**Comment by alecritson** [comment]
The provided media resolver has been removed in favour of Spatie's own. If you change the path resolver then you would need to regenerate the images.

**Comment by wychoong** [comment]
**note**
need to migrate/move the image files to Spatie's directory structure if changing from Lunar's `MediaPathResolver` to Spatie's `DefaultPathGenerator`
